# Generated by Django 4.1.3 on 2023-01-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'festival_image',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'post_image',
            },
        ),
        migrations.RemoveField(
            model_name='festival',
            name='Poster',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='festivalapp.post'),
        ),
        migrations.AlterField(
            model_name='optioncount',
            name='festival',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='option_count', serialize=False, to='festivalapp.festival'),
        ),
        migrations.AlterField(
            model_name='post',
            name='festival',
            field=models.ForeignKey(db_column='festival_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_festsival', to='festivalapp.festival'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AddField(
            model_name='postimage',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='festivalapp.post'),
        ),
        migrations.AddField(
            model_name='festivalimage',
            name='festival_id',
            field=models.ForeignKey(db_column='festival_id', on_delete=django.db.models.deletion.CASCADE, related_name='festival_images', to='festivalapp.festival'),
        ),
    ]
