# Generated by Django 4.1.3 on 2023-01-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='time_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='time_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
