# Generated by Django 4.1.3 on 2022-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0003_alter_post_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='ticket_open',
            field=models.DateTimeField(blank=True),
        ),
    ]
