# Generated by Django 4.1.3 on 2022-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0004_alter_festival_ticket_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='hits',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
