# Generated by Django 4.1.3 on 2022-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0006_alter_festival_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='Poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='festival',
            name='ticket_open',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
