# Generated by Django 4.1.3 on 2022-11-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0007_alter_festival_poster_alter_festival_ticket_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='Poster',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
