# Generated by Django 4.1.3 on 2022-11-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0009_alter_festival_ticket_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='Poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='festival',
            name='ticket_link',
            field=models.URLField(blank=True),
        ),
    ]
